name: CI build beta

on:
  push:
    branches:
      - master
      - develop
      - pczaj/CCP-2582
  schedule:
    - cron:  '0 2 * * *'
  repository_dispatch:
    types: [ uxkit-beta ]

jobs:
  build_frontend_beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.VOXEET_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.VOXEET_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.VOXEET_AWS_REGION }}
      - name: Set NPM token when logging to CodeArtifact
        run: |
          CODEARTIFACT_TOKEN=$(/usr/local/bin/aws codeartifact get-authorization-token --duration-seconds 1800 --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.CODEARTIFACT_DOMAIN_OWNER }} --region ${{ secrets.AWS_REGION }} --output text --query authorizationToken)
          echo "::add-mask::$CODEARTIFACT_TOKEN"
          echo "CUSTOM_REGISTRY_TOKEN=${{ secrets.CODEARTIFACT_NPM_SNAPSHOTS_REPOSITORY_TOKEN }}$CODEARTIFACT_TOKEN" >> $GITHUB_ENV
      - name: build and publish frontend Docker container for beta - production Web SDK
        uses: elgohr/Publish-Docker-Github-Action@2.22
        env:
          WEB_SDK_DIST_TAG: beta
          UX_KIT_DIST_TAG: beta
          CUSTOM_REGISTRY_URL: ${{ secrets.CODEARTIFACT_NPM_SNAPSHOTS_REPOSITORY_URL }}
        with:
          name: voxeet/voxeet-io-web
          dockerfile: Dockerfile
          workdir: frontend
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: CUSTOM_REGISTRY_URL,CUSTOM_REGISTRY_TOKEN,WEB_SDK_DIST_TAG,UX_KIT_DIST_TAG
          buildoptions: "--pull"
          tags: "${{ env.WEB_SDK_DIST_TAG }}"       
  build_frontend_beta_without_docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.VOXEET_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.VOXEET_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.VOXEET_AWS_REGION }}
      - name: Set NPM token when logging to CodeArtifact
        run: |
          CODEARTIFACT_TOKEN=$(/usr/local/bin/aws codeartifact get-authorization-token --duration-seconds 1800 --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.CODEARTIFACT_DOMAIN_OWNER }} --region ${{ secrets.AWS_REGION }} --output text --query authorizationToken)
          echo "::add-mask::$CODEARTIFACT_TOKEN"
          echo "CUSTOM_REGISTRY_TOKEN=${{ secrets.CODEARTIFACT_NPM_RELEASES_REPOSITORY_TOKEN }}$CODEARTIFACT_TOKEN" >> $GITHUB_ENV
      - name: build frontend for develop - beta Web SDK
        uses: actions/setup-node@v2
        with:
          node-version: "16.9.1"
      - run: |
          npm config set registry="$CUSTOM_REGISTRY_URL"
          npm config set $CUSTOM_REGISTRY_TOKEN
          npm config set always-auth true
          yarn add -E @voxeet/voxeet-web-sdk@$WEB_SDK_DIST_TAG;
          yarn add -E @voxeet/react-components@$UX_KIT_DIST_TAG
          yarn install
          yarn build
      - name: List files in the repository
        run: |
          ls ${{ env.working-directory }}
      - name: publish frontend for develop - beta Web SDK
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: dlb-capi-showcase 
          AWS_ACCESS_KEY_ID: ${{ secrets.VOXEET_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.VOXEET_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.VOXEET_AWS_REGION }}
          SOURCE_DIR: "frontend/dist"
          DEST_DIR: beta